modLoader = "kotori_scala"
loaderVersion = "[2.13.8,2.14.0)"
issueTrackerURL = "https://github.com/bdew-minecraft/factorium/issues"
license = "MIT"

[[mods]]
modId = "factorium"
version = "${file.jarVersion}"
displayName = "Factorium"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/factorium"
authors = "bdew"
description = '''
Ores, processing and various machines
'''

[[dependencies.factorium]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.factorium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.factorium]]
modId = "bdlib"
mandatory = true
versionRange = "[1.19.0,)"
ordering = "NONE"
side = "BOTH"

